print("das ist ein RUSSISCHE ROULETTE SPIEL")  # hier wird das spiel gestartet
print("wollen sie das spiel starten")       # hier wird das spiel gestartet
print("ja oder nein")   
eingabe = input()
if eingabe == "ja":
    print("1 führ eine andere reinfolge aus")
    print("2 führ einen neuen eintrag hinzu")
    print("3 lösche einen eintrag")
    print("4 ändere einen eintrag")
    print("5 speichere die ergebnisse in einer datei")
    print("6 beenden")
    eingabe = int(input())
    if eingabe == 1:
        print("1 führ eine andere reinfolge aus")
        print("2 führ einen neuen eintrag hinzu")
        print("3 lösche einen eintrag")
        print("4 ändere einen eintrag")
        print("5 speichere die ergebnisse in einer datei")
        print("6 beenden")
        eingabe = int(input())
        if eingabe == 1:
            print("1 führ eine andere reinfolge aus")
            print("2 führ einen neuen eintrag hinzu")
            print("3 lösche einen eintrag")
            print("4 ändere einen eintrag")
            print("5 speichere die ergebnisse in einer datei")
            print("6 beenden")
            eingabe = int(input())
            if eingabe == 1:
                print("1 führ eine andere reinfolge aus")
                print("2 führ einen neuen eintrag hinzu")
                print("3 lösche einen eintrag")
                print("4 ändere einen eintrag")
                print("5 speichere die ergebnisse in einer datei")
                print("6 beenden")
                eingabe = int(input())
                if eingabe == 1:
                    print("1 führ eine andere reinfolge aus")
                    print("2 führ einen neuen eintrag hinzu")
                    print("3 lösche einen eintrag")